# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  ? local-test-node-fe
  : build:
      target: development
    image: local-test-node-fe-development
    container_name: local-test-node-fe-development
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - ./app:/home/node/app
      - ./package.json:/home/node/package.json
